// auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_ERROR = "SIGNUP_ERROR"
// detail
export const FETCH_DETAIL = "LOADING_DETAIL"
// games
export const FETCH_UPCOMING = "FETCH_UPCOMING"
export const FETCH_POPULAR = "FETCH_POPULAR"
export const FETCH_NEWGAMES = "FETCH_NEWGAMES"
export const FETCH_SEARCHED = "FETCH_SEARCHED"
export const CLEAR_SEARCHED = "CLEAR_SEARCHED"
export const RESET_SEARCHED = "RESET_SEARCHED"
export const FETCH_AUTOCOMPLETE_SEARCH = "FETCH_AUTOCOMPLETE_SEARCH"
// favourites
export const ADD_FAVOURITE = "ADD_FAVOURITE"
export const FETCH_FAVOURITE = "FETCH_FAVOURITE"
export const DELETE_FAVOURITE = "DELETE_FAVOURITE"
// ui
export const TOGGLE_HEADER_DROPDOWN = "TOGGLE_HEADER_DROPDOWN"
export const CLOSE_HEADER_DROPDOWN = "CLOSE_HEADER_DROPDOWN"
export const OPEN_AUTOCOMPLETE = "OPEN_AUTOCOMPLETE"
export const CLOSE_AUTOCOMPLETE = "CLOSE_AUTOCOMPLETE"
export const TOGGLE_MOBILE_SEARCH_INPUT = "TOGGLE_MOBILE_SEARCH_INPUT"
export const CLOSE_MOBILE_SEARCH_INPUT = "CLOSE_MOBILE_SEARCH_INPUT"

export const START = "_START"
export const SUCCESS = "_SUCCESS"
export const FAIL = "_FAIL"




